### ISSUE TITLE
이미지를 선택해서 교체할 수 있는 기능 요청

### ISSUE THREAD

**Issue by ggg-hello** [sunshinekwon/test1#1]
텍스트박스와 버튼이 있고,
텍스트박스에 숫자 (1-3) 를 넣고 버튼을 누르면
숫자에 맞는 이미지가 화면에 출력되도록 기능을 만들어주세요.

이미지는 임의의 이미지 3장 구글에서 가져와서 등록하세요.

**Comment by sunshinekwon** [comment]
예

**Comment by sunshinekwon** [comment]
완료했습니다.
9acca0b3d6a2c0409c054439781009df5b941417
